### ISSUE TITLE
Packet loss

### ISSUE THREAD

**Issue by Noebas** [joshuar/pingbeat#6]
I beleve it will simply not log if the packet is not answered within the max rtt. Would it be posible to register it as lost or still writing it but with rtt of 999 or something like that.

**Comment by joshuar** [comment]
This will require some thought to implement.  Right now each event recorded in ES represents a measurement of RTT.  I'm not sure I'm comfortable recording zero or nil, or a negative value or some huge value to indicate loss that might interfere with any aggregations done on the data.  It might be better to record a "loss" in a different event.

**Comment by joshuar** [comment]
I believe tracking packet loss is addressed in **faster-main-loop** branch.  In that branch, the period config option becomes the max RTT  you'd expect, and any ICMP requests not responded to in that period are considered lost.  Then, in the Elasticsearch event, I write this as a `loss: true` bool field instead of the `rtt: somevalue` field.  You can then do you aggregations on how many events have `loss: true` to calculate your packet loss.

I'll probably merge that branch into master in the next few days.

**Comment by Noebas** [comment]
I have the new version running and this solution is perfect. Have RTT in one chart and the LOSS in another.
Ping to 150 hosts and a interval of 2 sec seems te be ok.
